### ISSUE TITLE
Binding tests need to be reviewed

### ISSUE THREAD

**Issue by Raiondesu** [KazanExpress/bound#1]
Tests for `binding.ts` feel rather incomplete to me. @kaskar2008, could you give them a nice, deep review?

**Comment by StefansArya** [comment]
Looks like we have a similar project
I also have written [a library](https://github.com/ScarletsFiction/ScarletsFrame) for DOM and object binding.
Maybe you will like it after see [the result](https://playcode.io/134963?tabs=console&resource-loader.js&output).

Currently it has compability problem on IE9, and I'm still looking a way to fix it.
Would you mind to working together @Raiondesu?

**Comment by StefansArya** [comment]
Looks like your library somewhat similar with my objective.
I also have written a library for data binding between DOM and data.
Maybe you will like it after see [the result](https://github.com/ScarletsFiction/ScarletsFrame#example).

Currently it has compability problem on IE9, and I'm still looking a way to fix it.
Would you mind to working together @Raiondesu?

**Comment by Raiondesu** [comment]
Hi, @StefansArya.

What exactly do you mean by "working together"?

**Comment by StefansArya** [comment]
Well,

It's like finding an issue, making changes or suggesting edit, and make the library being useful for the other.  Does it sound weird if I say "working together" :sweat_smile: ?

**Comment by Raiondesu** [comment]
Huh, it's okay. 😄 

I'll give it a look. 👍 

IE9 needs some polyfills, most probably.

**Comment by StefansArya** [comment]
Thanks friend! :+1:

Yes, the problem is because it's written in Vanilla JS with some ES6 code.
And some regex would need some enhancement too, because when I transpile it with babel it have some error.

**Comment by kaskar2008** [comment]
@Raiondesu OMG I'm so forgot about these tests. sry
